services:
  - type: web
    name: revi-ai-backend
    runtime: python3
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: APP_NAME
        value: REVI.AI
      - key: APP_VERSION
        value: 1.0.0
      - key: DEBUG
        value: False
      - key: CHROMA_DB_PATH
        value: ./chromadb
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760 